GEMINI_API_KEY="AIzaSyCUSxSxsDjgNN0-Teh2WL38x8QKoX9z-DY"
OPENAI_API_KEY="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"
